version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\ankrnetwork\dccncli

environment:
  GOPATH: c:\gopath

install:
  - echo %CD%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env

build_script:
  - go test -v -cover ./cmd/... ./commands/... ./do/... ./install/... ./pkg/... ./pluginhost/... .