FROM golang:alpine as builder

RUN apk update && apk add git && apk add --update bash && apk add openssh

WORKDIR $GOPATH/src/github.com/Ankr-network/dccn-cli/
COPY . $GOPATH/src/github.com/Ankr-network/dccn-cli/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-w -s" -o /go/bin/akrctl $GOPATH/src/github.com/Ankr-network/dccn-cli/cmd/dccncli/main.go

FROM scratch
COPY --from=builder /go/bin/akrctl /go/bin/akrctl
ENTRYPOINT ["/go/bin/akrctl"]