[[constraint]]
  branch = "feature/SWDEV-149-dashboard"
  name = "github.com/Ankr-network/dccn-common"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.3"

[[constraint]]
  branch = "master"
  name = "github.com/shiena/ansicolor"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/jwalterweatherman"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.16.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true
