# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # Build in Python container to install AWS CLI
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/Ankr-network/dccn-cli
    steps:
      - add_ssh_keys:
          fingerprints:
            - "91:de:2e:da:16:ab:18:de:71:0f:e2:bf:5f:44:5c:55"
            - "fb:e6:19:e7:21:de:65:fd:1f:60:22:6a:87:56:5e:36"
      - checkout
      - setup_remote_docker
      - run:
          name: copy ssh key
          command: |
            sudo cp ${HOME}/.ssh/id_rsa id_rsa
            sudo chmod 0644 id_rsa
      - run:
          name: Install AWSCLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --no-include-email --region us-west-2)

      - run:
          name: "Build & Push Docker Image"
          command: |
            docker build -t dccn-cli .
            docker tag dccn-cli:latest 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn_ecr:dccn-cli
            docker push 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn_ecr:dccn-cli
