# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # Build in Go base container
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/Ankr-network/dccn-cli
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Copy ssh key in the circleci build context
          command: |
            cp ${HOME}/.ssh/id_rsa id_rsa
      - run:
          name: Set dependency
          command: |
            dep ensure --vendor-only
      - run:
          name: Install AWSCLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: Log in to AWS ECR
          command: eval $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - run:
          name: "Test, Build & Push Docker Image"
          command: |
            BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
            SHA1_SHORT=$(git rev-parse --short HEAD)
            DATE=`date +%Y%m%d%H%M%S`
            URL_BRANCH=""
            if [[ ($BRANCH_NAME == "master") ]]
            then
              BRANCH_NAME="stage"
              URL_BRANCH="client.dccn.ankr.network"
              TENDERMINT_URL="chain.dccn.ankr.network"
            elif [[ ($BRANCH_NAME == "develop") ]]
            then
              BRANCH_NAME="dev"
              URL_BRANCH="client-stage.dccn.ankr.network"
              TENDERMINT_URL="chain-stage.dccn.ankr.network"
            else 
              BRANCH_NAME="feat"
              URL_BRANCH="client-dev.dccn.ankr.network"
              TENDERMINT_URL="chain-dev.dccn.ankr.network"
            fi
            export URL_BRANCH
            
            docker build --build-arg URL_BRANCH=${URL_BRANCH} --build-arg TENDERMINT_URL=${TENDERMINT_URL} -t ankrctl:$BRANCH_NAME .
            for TAG in $BRANCH_NAME $SHA1_SHORT $BRANCH_NAME$DATE; do
            docker tag ankrctl:$BRANCH_NAME $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/ankrctl:$TAG
            docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/ankrctl:$TAG
            done
            
