name: dccncli
version: "1.11.0"
summary: A command line tool for AnkrNetwork services
description: dccncli is a command line tool for AnkrNetwork servics using the API.
confinement: strict

apps:
  dccncli:
    command: bin/dccncli
    plugs: [network]

parts:
  dccncli:
    source: ..
    plugin: go
    go-importpath: github.com/Ankr-network/dccn-cli
    build-packages: [git]
    go-packages: [github.com/Ankr-network/dccn-cli/cmd/dccncli]
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bash_completions
      mkdir -p $SNAPCRAFT_PART_INSTALL/zsh_completions
      dccncli completion bash > $SNAPCRAFT_PART_INSTALL/bash_completions/dccncli
      dccncli completion zsh > $SNAPCRAFT_PART_INSTALL/zsh_completions/dccncli
